
# Optimize OpenSora batch size for faster inference [2024-08-29T18:03:00]

# Improve CogVideo consistency with fixed seed [2024-09-02T12:54:00]

# Evaluate PyramidFlow across 5 prompt types [2024-09-04T15:24:00]

# Add duration limit per model run [2024-09-08T18:17:00]

# Embed model name in S3 video object keys [2024-09-09T18:24:00]

# Add prompt hover tooltip to video thumbnails [2024-09-12T10:21:00]

# Clarify AWS + HuggingFace setup steps in README [2024-09-14T10:49:00]

# Add test prompts covering weather and lighting changes [2024-09-18T15:18:00]

# Run black formatter on backend scripts [2024-09-21T11:26:00]

# Optimize OpenSora batch size for faster inference [2024-09-24T16:57:00]

# Improve CogVideo consistency with fixed seed [2024-09-28T15:06:00]

# Evaluate PyramidFlow across 5 prompt types [2024-10-01T10:11:00]

# Add duration limit per model run [2024-10-05T12:21:00]

# Embed model name in S3 video object keys [2024-10-07T17:36:00]

# Add prompt hover tooltip to video thumbnails [2024-10-11T17:52:00]
