
# Optimize OpenSora batch size for faster inference [2024-08-29T18:03:00]

# Improve CogVideo consistency with fixed seed [2024-09-02T12:54:00]

# Evaluate PyramidFlow across 5 prompt types [2024-09-04T15:24:00]

# Add duration limit per model run [2024-09-08T18:17:00]

# Embed model name in S3 video object keys [2024-09-09T18:24:00]

# Add prompt hover tooltip to video thumbnails [2024-09-12T10:21:00]
