
# Add OpenSora preset for 16:9 format [2024-08-30T12:35:00]

# Enable multi-GPU inference for CogVideo [2024-09-02T18:21:00]

# Add base inference loop for Mochi model [2024-09-05T11:29:00]

# Improve error handling across all models [2024-09-08T10:23:00]

# Store generation logs alongside S3 videos [2024-09-10T10:33:00]

# Fix video playback glitch on Chrome [2024-09-13T10:49:00]

# Add usage example to README for inference script [2024-09-15T15:28:00]

# Evaluate each model with identical prompt set [2024-09-19T17:25:00]

# Fix import warnings in utils.py [2024-09-21T14:59:00]

# Add OpenSora preset for 16:9 format [2024-09-24T14:43:00]

# Enable multi-GPU inference for CogVideo [2024-09-28T10:37:00]

# Add base inference loop for Mochi model [2024-10-01T14:09:00]

# Improve error handling across all models [2024-10-05T15:20:00]
